# Example Site settings

#google_analytics: UA-NNNNNNNN-N
title: 'briSee'
description: "cybersecurity blog about penetration testing, red teaming, blue teaming, and things."
url: "https://brisee.github.io"

header_pages:
- index.md
- categories.html
- about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light

footer: 'follow me on <a href="https://twitter.com/bri5ee">twitter</a>'
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-toc
kramdown:
  parse_block_html: true
